### ISSUE TITLE
Archive page doesn't have space between sermons in Divi

### ISSUE THREAD

**Issue by robertmain** [WP-for-Church/Sermon-Manager#182]
On the sermon archive page, there are no spaces between the posts when using Divi. The ~hack~ fix for this was to add

```css
article.wpfc_sermon {
    margin-bottom: 60px;
}
```

to my Divi CSS, however I wondered if there was a better solution in the works? I'm happy to put a PR together if not..
